import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/header/header";
import AppProvder from "@/components/context/AppContext";

import Head from "next/head";

import Script from "next/script";
import { Toaster } from "react-hot-toast";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.PNG" />
      </Head>
      <body className={poppins.className}>
        <main className="max-w-4xl mx-auto  px-2">
          <AppProvder>
            <Toaster />
            <Header />
            {children}
            <footer className="text-center border-t p-8 text-gray-600">
              &copy; 2023 All right reserved
            </footer>
          </AppProvder>
        </main>
      </body>
    </html>
  );
}
